---
abstract: 'Common API for data with semantics attached to them'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Differences: 0
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Semantic
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Complex: 0
  Data::Inherited: 0
  Regexp::Common: 0
  Test::CompanionClasses: 0.03
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-Semantic
  homepage: http://search.cpan.org/dist/Data-Semantic/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/data-semantic.git
version: 0.04
