---
abstract: 'Common API for data with semantics attached to them'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101582, CPAN::Meta::Converter version 2.101591'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Semantic
provides:
  Data::Semantic:
    file: lib/Data/Semantic.pm
    version: 1.101620
  Data::Semantic::RegexpAdapter:
    file: lib/Data/Semantic/RegexpAdapter.pm
    version: 1.101620
  Data::Semantic::Test:
    file: lib/Data/Semantic/Test.pm
    version: 1.101620
requires:
  Class::Accessor::Complex: 0
  Data::Inherited: 0
  Regexp::Common: 0
  Test::CompanionClasses::Base: 0
  Test::More: 0
  constant: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-Semantic
  homepage: http://search.cpan.org/dist/Data-Semantic/
  repository: http://github.com/hanekomu/Data-Semantic
version: 1.101620
